import type { Contract } from "../../features/bdd/schema"
import type {
  BddPipelineResult,
  BddPipelineStageName,
  BddPipelineStageResult,
} from "./types"

export function stageStatusBadge(stage: BddPipelineStageResult): string {
  if (stage.status === "completed" && stage.testsFailed === 0) return "completed"
  if (stage.status === "timeout") return "timeout"
  return "failed"
}

export function buildAnnotationsSection(contract: Contract): string {
  const lines: string[] = []
  const ann = contract.annotations

  if (ann.api) {
    lines.push("### API")
    lines.push("")
    if (ann.api.endpoints && ann.api.endpoints.length > 0) {
      lines.push("| Method | Path | Request | Response | Description |")
      lines.push("| --- | --- | --- | --- | --- |")
      for (const ep of ann.api.endpoints) {
        lines.push(
          `| ${ep.method} | \`${ep.path}\` | ${ep.request ?? "—"} | ${ep.response ?? "—"} | ${ep.description ?? ""} |`,
        )
      }
      lines.push("")
    }
    if (ann.api.responses && ann.api.responses.length > 0) {
      lines.push("**Responses:**")
      lines.push("")
      for (const r of ann.api.responses) {
        lines.push(`- \`${r.status}\` (${r.format}) — ${r.description ?? ""}`)
      }
      lines.push("")
    }
  }

  if (ann.ui) {
    lines.push("### UI")
    lines.push("")
    if (ann.ui.routes && ann.ui.routes.length > 0) {
      lines.push("| Route | Path |")
      lines.push("| --- | --- |")
      for (const r of ann.ui.routes) {
        lines.push(`| ${r.name} | \`${r.path}\` |`)
      }
      lines.push("")
    }
    if (ann.ui.testIds && ann.ui.testIds.length > 0) {
      lines.push("**Test IDs:**")
      lines.push("")
      for (const t of ann.ui.testIds) {
        lines.push(`- \`${t.value}\` — ${t.name}`)
      }
      lines.push("")
    }
    if (ann.ui.strings && ann.ui.strings.length > 0) {
      lines.push("**Strings:**")
      lines.push("")
      for (const s of ann.ui.strings) {
        lines.push(`- **${s.key}:** ${s.value}`)
      }
      lines.push("")
    }
  }

  if (ann.state) {
    lines.push("### State")
    lines.push("")
    if (ann.state.variables && ann.state.variables.length > 0) {
      lines.push("| Variable | Type | Default |")
      lines.push("| --- | --- | --- |")
      for (const v of ann.state.variables) {
        const def = v.default === undefined ? "—" : JSON.stringify(v.default)
        lines.push(`| ${v.name} | ${v.type} | ${def} |`)
      }
      lines.push("")
    }
    if (ann.state.transitions && ann.state.transitions.length > 0) {
      lines.push("**Transitions:**")
      lines.push("")
      for (const t of ann.state.transitions) {
        lines.push(`- \`${t.from}\` → \`${t.to}\` (trigger: ${t.trigger})`)
      }
      lines.push("")
    }
  }

  if (ann.assumptions && ann.assumptions.length > 0) {
    lines.push("### Assumptions (from contract)")
    lines.push("")
    for (const a of ann.assumptions) {
      lines.push(`- ${a}`)
    }
    lines.push("")
  }

  if (lines.length === 0) {
    lines.push("_No annotations recorded in the contract._")
    lines.push("")
  }

  return lines.join("\n")
}

export function buildFrontendMappingSection(
  contract: Contract,
  stage: BddPipelineStageResult,
): string {
  const lines: string[] = []
  const ui = contract.annotations.ui
  lines.push("| Source | Mapped to | Notes |")
  lines.push("| --- | --- | --- |")
  if (ui?.routes) {
    for (const r of ui.routes) {
      lines.push(`| route \`${r.path}\` | \`src/components/${r.name}.tsx\` | generated by frontend stage |`)
    }
  }
  if (ui?.testIds) {
    for (const t of ui.testIds) {
      lines.push(
        `| testId \`${t.value}\` | \`data-testid=${t.value}\` usage in component | \`${t.name}\` |`,
      )
    }
  }
  if (lines.length === 2) {
    lines.push("| _(no UI annotations)_ | _(not generated)_ | UNUSED |")
  }
  lines.push("")
  lines.push(`**Frontend stage status:** ${stageStatusBadge(stage)}`)
  if (stage.error) {
    lines.push(`**Frontend stage error:** ${stage.error}`)
  }
  lines.push("")
  return lines.join("\n")
}

export function buildBackendMappingSection(
  contract: Contract,
  stage: BddPipelineStageResult,
): string {
  const lines: string[] = []
  const api = contract.annotations.api
  lines.push("| Source | Mapped to | Notes |")
  lines.push("| --- | --- | --- |")
  if (api?.endpoints) {
    for (const ep of api.endpoints) {
      const svcName =
        ep.path
          .replace(/[{}]/g, "")
          .replace(/[^a-zA-Z0-9]+/g, "_")
          .replace(/^_|_$/g, "") || "service"
      lines.push(
        `| ${ep.method} \`${ep.path}\` | \`src/services/${svcName}.ts\` | generated by backend stage |`,
      )
    }
  }
  if (api?.responses) {
    for (const r of api.responses) {
      lines.push(`| response \`${r.status}\` (${r.format}) | type in service | ${r.description ?? ""} |`)
    }
  }
  if (lines.length === 2) {
    lines.push("| _(no API annotations)_ | _(not generated)_ | NOT IMPLEMENTED |")
  }
  lines.push("")
  lines.push(`**Backend stage status:** ${stageStatusBadge(stage)}`)
  if (stage.error) {
    lines.push(`**Backend stage error:** ${stage.error}`)
  }
  lines.push("")
  return lines.join("\n")
}

export function buildTestCoverageSection(result: BddPipelineResult): string {
  const lines: string[] = []
  const order: BddPipelineStageName[] = ["tests", "frontend", "backend"]
  lines.push("| Stage | Runner | Tests run | Tests passed | Tests failed | Status |")
  lines.push("| --- | --- | --- | --- | --- | --- |")
  for (const stageName of order) {
    const s = result.stages[stageName]
    const runner = stageName === "tests" ? "cucumber" : "vitest"
    lines.push(
      `| ${stageName} | ${runner} | ${s.testsRun} | ${s.testsPassed} | ${s.testsFailed} | ${stageStatusBadge(s)} |`,
    )
  }
  lines.push("")
  return lines.join("\n")
}

export function buildAssumptionsSection(contract: Contract): string {
  const lines: string[] = []
  const a = contract.annotations.assumptions ?? []
  if (a.length === 0) {
    lines.push("_No explicit assumptions recorded in the contract._")
    lines.push("")
    return lines.join("\n")
  }
  for (const x of a) {
    lines.push(`- ${x}`)
  }
  lines.push("")
  return lines.join("\n")
}

export function buildAmbiguitiesSection(result: BddPipelineResult): string {
  const lines: string[] = []
  if (result.ambiguities.length === 0) {
    lines.push("_No ambiguities surfaced by the pipeline._")
    lines.push("")
    return lines.join("\n")
  }
  for (const amb of result.ambiguities) {
    const lead = amb.split(":")[0]?.trim() || "Note"
    const rest = amb.includes(":") ? amb.slice(amb.indexOf(":") + 1).trim() : amb
    lines.push(`- **${lead}:** ${rest}`)
  }
  lines.push("")
  return lines.join("\n")
}

export function buildFilesGeneratedSection(
  result: BddPipelineResult,
  featureDir: string,
  order: readonly BddPipelineStageName[],
): string {
  const lines: string[] = []
  lines.push("```")
  lines.push(`${featureDir}/`)
  lines.push(`├── ANALYSIS.md`)
  for (const stageName of order) {
    const s = result.stages[stageName]
    if (s.filesCreated.length === 0) continue
    lines.push(`├── ${stageName}/`)
    for (const f of s.filesCreated) {
      lines.push(`│   └── ${f}`)
    }
  }
  lines.push("```")
  lines.push("")
  return lines.join("\n")
}
