// Re-export the strict annotation types and value schemas from schema.ts.
// This barrel is the single import surface for downstream code (tools,
// agents, skill templates). The legacy `AnnotationApi` / `AnnotationUi` /
// `AnnotationState` types are gone — use the typed element schemas instead.
export type {
  ApiAnnotations,
  ApiEndpoint,
  ApiResponse,
  Background,
  Contract,
  ContractAnnotations,
  ExampleRow,
  Feature,
  HttpMethod,
  ResponseFormat,
  Rule,
  Scenario,
  StateAnnotations,
  StateTransition,
  StateVariable,
  Step,
  StepKeyword,
  UiAnnotations,
  UiRoute,
  UiString,
  UiTestId,
  VarType,
} from "./schema"

export {
  ApiAnnotationsSchema,
  ApiEndpointSchema,
  ApiResponseSchema,
  CamelCaseSchema,
  ContractAnnotationsSchema,
  ContractSchema,
  DottedKebabSchema,
  FeatureSchema,
  HttpMethodSchema,
  KebabCaseSchema,
  ResponseFormatSchema,
  ScenarioSchema,
  StateAnnotationsSchema,
  StateTransitionSchema,
  StateVariableSchema,
  StepSchema,
  UiAnnotationsSchema,
  UiRouteSchema,
  UiStringSchema,
  UiTestIdSchema,
  UrlPathSchema,
  VarTypeSchema,
} from "./schema"
