#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Batch BDD test runner for the demos/bdd/ tree.
#
# Discovers every feature subdirectory that contains a run-tests.sh, then
# invokes each one in sequence. Each per-feature runner is self-contained: it
# starts its own preview-server, waits for it, runs cucumber-js, and tears it
# down on exit. A failure in one feature does not abort the others.
#
# Generated by the bdd-tests pipeline when the input is a directory of
# multiple .feature files.
#
# Usage (from the repo root):
#   bash demos/bdd/run-tests.sh                          # run all features
#   bash demos/bdd/run-tests.sh --tags @happy-path       # forward tag filter
#   BDD_FEATURE=login bash demos/bdd/run-tests.sh        # run a single feature
#
# Env vars (all optional):
#   BDD_FEATURE    Restrict the run to a single feature subdir (e.g. "login")
#   BDD_ARGS       Extra args appended to the cucumber-js invocation
# ---------------------------------------------------------------------------
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FEATURE_FILTER="${BDD_FEATURE:-}"

TOTAL_PASS=0
TOTAL_FAIL=0
FAILED_FEATURES=()

shopt -s nullglob
for feature_dir in "$SCRIPT_DIR"/*/; do
  feature_name="$(basename "$feature_dir")"
  runner="$feature_dir/run-tests.sh"

  # Skip subdirs that do not have a generated runner.
  if [[ ! -f "$runner" ]]; then
    continue
  fi

  # Skip features not matching BDD_FEATURE filter (if set).
  if [[ -n "$FEATURE_FILTER" && "$feature_name" != "$FEATURE_FILTER" ]]; then
    echo "[bdd] Skipping $feature_name (BDD_FEATURE=$FEATURE_FILTER)"
    continue
  fi

  echo ""
  echo "============================================================"
  echo "[bdd] Feature: $feature_name"
  echo "============================================================"

  # Each per-feature runner exits with its own cucumber-js status.
  # set -e is off so a single feature failure does not stop the loop.
  if bash "$runner" "$@"; then
    TOTAL_PASS=$((TOTAL_PASS + 1))
  else
    TOTAL_FAIL=$((TOTAL_FAIL + 1))
    FAILED_FEATURES+=("$feature_name")
  fi
done

echo ""
echo "============================================================"
echo "[bdd] Summary: $TOTAL_PASS passed, $TOTAL_FAIL failed"
if [[ ${#FAILED_FEATURES[@]} -gt 0 ]]; then
  echo "[bdd] Failed: ${FAILED_FEATURES[*]}"
fi
echo "============================================================"

[[ $TOTAL_FAIL -eq 0 ]]
