#!/usr/bin/env node

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const APP_ROOT = resolve(__dirname, "..");
const MATRIX_ROOT = resolve(__dirname, "..", "..", "..");

const SCHEMA_SOURCE = resolve(MATRIX_ROOT, "dist", "matrixx.schema.json");
const SCHEMA_OUTPUT_DIR = resolve(APP_ROOT, "src", "lib", "config");
const SCHEMA_OUTPUT = resolve(SCHEMA_OUTPUT_DIR, "schema.json");
const VERSION_OUTPUT = resolve(SCHEMA_OUTPUT_DIR, "schema-version.ts");

const MATRIX_PACKAGE = resolve(MATRIX_ROOT, "package.json");

let exitCode = 0;

function fail(message) {
  console.error(`[sync-schema] ERROR: ${message}`);
  exitCode = 1;
}

// Read Matrixx version
let matrixxVersion;
try {
  const pkg = JSON.parse(readFileSync(MATRIX_PACKAGE, "utf-8"));
  matrixxVersion = pkg.version;
  if (!matrixxVersion) {
    fail(`"version" field missing in ${MATRIX_PACKAGE}`);
  }
} catch (err) {
  fail(`Cannot read ${MATRIX_PACKAGE}: ${err.message}`);
}

// Read schema file
let schemaContent;
try {
  schemaContent = readFileSync(SCHEMA_SOURCE, "utf-8");
  // Validate it's parseable JSON
  JSON.parse(schemaContent);
} catch (err) {
  fail(`Cannot read or parse ${SCHEMA_SOURCE}: ${err.message}`);
}

if (exitCode !== 0) {
  process.exit(exitCode);
}

// Ensure output directory exists
mkdirSync(SCHEMA_OUTPUT_DIR, { recursive: true });

// Write schema.json
writeFileSync(SCHEMA_OUTPUT, schemaContent, "utf-8");
console.log(
  `[sync-schema] ✓ schema.json (${(schemaContent.length / 1024).toFixed(0)} KB)`,
);

// Write schema-version.ts
const versionStamp = `// Auto-generated by scripts/sync-schema.mjs — do not edit manually
// Compatible with opencode-matrixx v${matrixxVersion}

export const SCHEMA_VERSION = "${matrixxVersion}" as const
export const SCHEMA_SOURCE = "${SCHEMA_SOURCE}" as const
`;

writeFileSync(VERSION_OUTPUT, versionStamp, "utf-8");
console.log(
  `[sync-schema] ✓ schema-version.ts (compatible with v${matrixxVersion})`,
);

console.log("[sync-schema] ✓ Schema sync complete");
