#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Local test runner for the login BDD feature.
# Generated by the bdd-tests pipeline alongside the Dockerfile.
#
# Usage (from the repo root):
#   bash demos/bdd/login/run-tests.sh                        # all scenarios
#   bash demos/bdd/login/run-tests.sh --tags @happy-path     # tag filter
#   bash demos/bdd/login/run-tests.sh --tags "not @unhappy"  # exclude tag
#
# Env vars (all optional):
#   BDD_BASE_URL    Base URL of the running app (default http://localhost:4000)
#   PREVIEW_PORT    Port the preview server binds to (default 4000)
#   BDD_ARGS        Extra args appended to the cucumber-js invocation
# ---------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
PREVIEW_PORT="${PREVIEW_PORT:-4000}"
PREVIEW_SERVER="$SCRIPT_DIR/components/preview-server.ts"
LOG_DIR="$SCRIPT_DIR/reports"
LOG_FILE="$LOG_DIR/preview-server.log"

mkdir -p "$LOG_DIR"

# --- 1. Start the preview server (the "app" the tests talk to) ---
echo "[bdd] Starting preview server on :$PREVIEW_PORT ..."
PREVIEW_PORT="$PREVIEW_PORT" bun run "$PREVIEW_SERVER" >"$LOG_FILE" 2>&1 &
PREVIEW_PID=$!

cleanup() {
  local exit_code=$?
  if kill -0 "$PREVIEW_PID" 2>/dev/null; then
    echo "[bdd] Stopping preview server (pid $PREVIEW_PID) ..."
    kill "$PREVIEW_PID" 2>/dev/null || true
    wait "$PREVIEW_PID" 2>/dev/null || true
  fi
  exit "$exit_code"
}
trap cleanup EXIT INT TERM

# --- 2. Wait for the preview server to be reachable (max 30s) ---
echo "[bdd] Waiting for http://localhost:$PREVIEW_PORT/ ..."
for _ in $(seq 1 60); do
  if curl -fsS "http://localhost:$PREVIEW_PORT/login" >/dev/null 2>&1; then
    echo "[bdd] Preview server is up."
    break
  fi
  sleep 0.5
done
if ! curl -fsS "http://localhost:$PREVIEW_PORT/login" >/dev/null 2>&1; then
  echo "[bdd] ERROR: preview server did not start in time. See $LOG_FILE"
  exit 1
fi

# --- 3. Run cucumber against this feature ---
cd "$SCRIPT_DIR"
echo "[bdd] Running cucumber-js ..."
exec npx cucumber-js . \
  --require 'tests/**/*.ts' \
  --require 'tests/**/*.steps.ts' \
  --require-module tsx/esm \
  --format '@cucumber/pretty-formatter' \
  --format "html:$LOG_DIR/cucumber-report.html" \
  ${BDD_ARGS:-} \
  "$@"
