import { z } from "zod"

export const BuiltinAgentNameSchema = z.enum([
  "morpheus",
  "keymaker",
  "oracle",
  "merovingian",
  "operator",
  "trinity",
  "construct",
  "seraph",
  "smith",
  "architect",
  "cipher",
  "niobe",
  "sentinel",
  "zion",
])

export const BuiltinSkillNameSchema = z.enum([
  "playwright",
  "agent-browser",
  "dev-browser",
  "frontend-ui-ux",
  "git-master",
  "dsl-core",
  "dsl-grammar",
  "dsl-codegen",
  "dsl-metamodel",
  "dsl-tooling",
  "eu-horizon",
  "academic-review",
  "deliverable-writing",
  "project-management",
  "technical-lead",
  "academic-writing",
  "research-methodology",
  "literature-review",
  "grant-writing",
  "scientific-presentation",
  "data-management-plan",
  "ip-exploitation",
  "dsl-textx-ecosystem",
  "dsl-pyecore-advanced",
  "dsl-model-transformation",
  "dsl-testing",
  "dsl-validation",
  "dsl-composition",
  "security-core",
  "security-secrets",
  "security-sast",
  "security-dast",
  "security-dependencies",
  "security-api",
  "security-crypto",
  "security-infra",
  "security-review",
  "crypto-market-analysis",
  "crypto-trading",
  "crypto-onchain",
])

export const OverridableAgentNameSchema = z.enum([
  "build",
  "plan",
  "morpheus",
  "keymaker",
  "mouse",
  "OpenCode-Builder",
  "oracle",
  "seraph",
  "smith",
  "merovingian",
  "operator",
  "trinity",
  "construct",
  "architect",
  "cipher",
  "niobe",
  "sentinel",
  "zion",
])

export const AgentNameSchema = BuiltinAgentNameSchema
export type AgentName = z.infer<typeof AgentNameSchema>

export type BuiltinSkillName = z.infer<typeof BuiltinSkillNameSchema>
