import { z } from "zod"

const HookNameEnum = z.enum([
  "task-continuation-enforcer",
  "todo-continuation-enforcer",
  "context-window-monitor",
  "session-recovery",
  "session-notification",
  "comment-checker",
  "tool-output-truncator",
  "directory-agents-injector",
  "empty-task-response-detector",
  "think-mode",
  "context-window-limit-recovery",
  "preemptive-compaction",
  "rules-injector",
  "background-notification",
  "background-task-blocker",
  "auto-update-checker",
  "startup-toast",
  "keyword-detector",
  "agent-usage-reminder",
  "non-interactive-env",
  "interactive-bash-session",

  "thinking-block-validator",
  "matrix-loop",
  "category-skill-reminder",

  "compaction-context-injector",
  "compaction-todo-preserver",
  "auto-slash-command",
  "edit-error-recovery",
  "delegate-task-retry",
  "oracle-md-only",
  "plan-persister",
	"mouse-notepad",
  "start-work",
  "architect",
  "unstable-agent-babysitter",
  "task-resume-info",
  "stop-continuation-guard",
  "tasks-todowrite-disabler",
  "write-existing-file-guard",
  "anthropic-effort",
  "hashline-read-enhancer",
  "secret-leak-guard",
  "input-secret-guard",
  "env-context-injector",
  "env-file-write-guard",
  "json-error-recovery",
  "bash-file-read-guard",
  "runtime-fallback",
  "read-image-resizer",
  "webfetch-redirect-guard",
  "hashline-edit-diff-enhancer",
  "tool-pair-validator",
  "quality-gate",
  "task-notepad",
  "design-intent-preserver",
  "rtk-bash-rewriter",
  "evolution-watcher",
  "evolution-compressor",
  "evolution-hitl",
  "context-mode-enforcer",
  "context-mode-enforcer",
  "task-edit-guard",
  "failure-counter",
])

// Deprecated alias — remove in v2.7 (BREAKING: rename anthropic- → generic)
export const HookNameSchema = z.union([
  HookNameEnum,
  z.literal("anthropic-context-window-limit-recovery").transform(() => 'context-window-limit-recovery' as const),
])

export type HookName = z.infer<typeof HookNameSchema>

