import { z } from "zod"

export const HookNameSchema = z.enum([
  "todo-continuation-enforcer",
  "context-window-monitor",
  "session-recovery",
  "session-notification",
  "comment-checker",
  "grep-output-truncator",
  "tool-output-truncator",
  "question-label-truncator",
  "directory-agents-injector",
  "directory-readme-injector",
  "empty-task-response-detector",
  "think-mode",
  "anthropic-context-window-limit-recovery",
  "preemptive-compaction",
  "rules-injector",
  "background-notification",
  "auto-update-checker",
  "startup-toast",
  "keyword-detector",
  "agent-usage-reminder",
  "non-interactive-env",
  "interactive-bash-session",

  "thinking-block-validator",
  "matrix-loop",
  "category-skill-reminder",

  "compaction-context-injector",
  "compaction-todo-preserver",
  "auto-slash-command",
  "edit-error-recovery",
  "delegate-task-retry",
  "prometheus-md-only",
  "mouse-notepad",
  "start-work",
  "architect",
  "unstable-agent-babysitter",
  "task-reminder",
  "task-resume-info",
  "stop-continuation-guard",
  "tasks-todowrite-disabler",
  "write-existing-file-guard",
  "anthropic-effort",
  "hashline-read-enhancer",
  "secret-leak-guard",
  "env-file-write-guard",
  "json-error-recovery",
  "bash-file-read-guard",
  "todo-description-override",
  "runtime-fallback",
  "read-image-resizer",
  "webfetch-redirect-guard",
  "hashline-edit-diff-enhancer",
  "tool-pair-validator",
  "quality-gate",
  "task-notepad",
  "design-intent-preserver",
])

export type HookName = z.infer<typeof HookNameSchema>
