// Auto-generated by scripts/sync-schema.mjs — do not edit manually
// Compatible with opencode-matrixx v2.6.11

export const SCHEMA_VERSION = "2.6.11" as const
export const SCHEMA_SOURCE = "/home/klpanagi/matrixx/dist/matrixx.schema.json" as const
