// Auto-generated by scripts/sync-schema.mjs — do not edit manually
// Compatible with opencode-matrixx v2.6.4

export const SCHEMA_VERSION = "2.6.4" as const
export const SCHEMA_SOURCE = "/home/klpanagi/matrixx/dist/matrixx.schema.json" as const
