export const BDD_PIPELINE_TEMPLATE = `# /bdd-pipeline

Full BDD pipeline: generate contract, tests, frontend, and backend from one or more .feature files.

## Usage

Single file:
\`\`\`
/bdd-pipeline <feature-path> [--force]
\`\`\`

Batch (directory or glob):
\`\`\`
/bdd-pipeline <dir> --out <out-dir> [--force]
/bdd-pipeline "<dir>/**/*.feature" --out <out-dir> [--force]
\`\`\`

## Pipeline Steps
1. /bdd-contract <input> -- Parse feature(s) -> generate Contract JSON AND LLM-enrich annotations (api/ui/state/assumptions) via the bdd-contract skill. The bdd_create_contract tool is deterministic and writes empty annotations; the bdd-contract skill loaded into the running agent must fill them via LLM inference from feature content (name, scenarios, tags, step text) before moving to step 2.
2. **Run bdd-tests, bdd-frontend, and bdd-backend in parallel** as 3 background subagents (\`task(run_in_background=true)\`). Each subagent has a contract JSON as input and:
   - generates its respective artefacts (step defs + page objects + cucumber.cjs + Dockerfile + run-tests.sh | React components + *.test.tsx + preview-server.ts | typed Zod API service + *.test.ts)
   - runs its own test suite as the FINAL step of its work (3 retries on failure, then report)
   - returns a structured { stage, files_created, tests_passed, tests_failed, test_output } report
   Each stage is independent -- no shared state between the three subagents.

## Aggregation
When the 3 subagents return, aggregate:
- **PASS** if all 3 stages report tests_passed == tests_total
- **FAIL** otherwise, with a per-stage breakdown: which stage(s) failed, how many tests failed, and the first 50 lines of the failing test output per stage
Report the aggregated result in the pipeline's final response. Do NOT mark the pipeline as successful if any of the 3 stages failed.

For batch input (multiple .feature files), iterate the contract phase per file (deterministic + fast), then for each contract spawn the 3 parallel subagents above. Subagents across different features can themselves run in parallel up to 5 concurrent.

For batch input (multiple .feature files), iterate the contract phase per file (deterministic + fast), then for each contract spawn the 3 parallel subagents above. Subagents across different features can themselves run in parallel up to 5 concurrent.

## Per-Feature Analysis Report (REQUIRED output)
After the 3 parallel subagents return AND the aggregation step reports PASS or FAIL, the pipeline MUST produce a per-feature Markdown report at \`<out-dir>/<feature>/ANALYSIS.md\`. This is the document the product owner / tech lead reads to (a) understand what the pipeline inferred about their feature and (b) catch ambiguities before the code gets merged.

The report has these sections, in order:

### 1. Header
\`\`\`markdown
# Feature Analysis: <feature.name>

> Auto-generated by /bdd-pipeline on <ISO timestamp>
> Source: \`<relative path to .feature>\`
> Contract: \`<relative path to .feature.contract.json>\`
> Pipeline status: PASS | FAIL
\`\`\`

### 2. Overview
A 3-4 line bulleted block: name, description, scenario count, tag list, pipeline status badge.

### 3. Contract Annotations
Re-state the contract's inferred annotations as tables, NOT raw JSON. One table per annotation category that has at least one entry. Categories: API Endpoints, API Responses, UI Routes, UI Test IDs, UI Strings, State Variables, State Transitions, Assumptions. If a category is empty, omit its table (do not show 'none').

### 4. Frontend Mapping (Feature -> Components)
A table that maps each \`annotations.ui.routes[]\` entry to the generated component file. For each row, list the component path, the test file path, and the row's status (PASS if the unit tests for that component pass, FAIL otherwise). Add a second table that maps each \`annotations.ui.testIds[]\` entry to the component file that uses the \`data-testid={value}\` attribute. If a testId is defined in the contract but not used in any component, flag it as 'UNUSED' -- that's an ambiguity for the human reviewer.

### 5. Backend API Mapping (Feature -> Endpoints)
A table that maps each \`annotations.api.endpoints[]\` entry to the generated service file. For each row, list the service file path, the test file path, and the row's status. Add a second table for \`annotations.api.responses[]\` -> the response shapes that the service actually returns. Missing responses flag as 'NOT IMPLEMENTED' -- another ambiguity.

### 6. Test Coverage
A single summary table with one row per pipeline stage (Frontend unit, Backend unit, E2E cucumber) and columns: stage, runner (e.g. \`bun test components/\`), tests_run, tests_passed, tests_failed, status.

### 7. Assumptions
A flat bullet list of every entry in \`annotations.assumptions\`. One bullet per assumption. No additional commentary here -- the Ambiguities section is for that.

### 8. Ambiguities & Open Questions (THE MOST IMPORTANT SECTION)
This is where the LLM surfaces judgment calls, NOT facts. The report must call out:

- **Inferences where the contract was unclear** -- e.g. 'The feature mentions "session" but never says what type. Inferred as \`object\` based on the assumption that it holds \`{ token, expiresAt }\`. Confirm with backend.'
- **Multiple plausible interpretations** -- e.g. 'Step 3 says "the user is redirected to the dashboard". This could be an SPA route change (no HTTP redirect) OR a 302 HTTP redirect. Generated the SPA interpretation. Confirm with frontend lead.'
- **Contract fields that are unused or under-specified** -- e.g. '\`annotations.ui.testIds\` declares \`submit-button\` but the generated \`LoginPage\` uses \`data-testid="login-submit-button"\` (per the \`bdd-tests\` page object). Either the testIds annotation should be updated to match, or the component should be re-generated to use the annotation value.'
- **State transitions with multiple possible triggers** -- e.g. '\`state.transitions\` has \`{ from: "new-session-init", to: "authenticated" }\` with no trigger. Inferred the trigger is "successful POST /api/v1/auth/login returning 2xx". If the actual trigger is different (token refresh, OAuth callback, etc.), the state machine needs review.'

Each ambiguity is a bullet with a bold lead-in and a one-paragraph explanation. The LLM is encouraged to flag anything it had to guess at -- the goal is that a human reviewer never has to wonder 'why did the pipeline make this decision'.

### 9. Files Generated
A \`tree -L 2\`-style listing of the feature output directory, showing the directory structure with key file types. Truncate long file contents (just show file names). The goal is 'where do I find what' -- not a full file dump.

## Output
All outputs: per-feature Contract JSON, test files, components, and API services, AND the per-feature ANALYSIS.md report. For batch input, everything is organized under \`<out-dir>/<feature>/\`.
## Output
All outputs: per-feature Contract JSON, test files, components, and API services. For batch input, everything is organized under \`<out-dir>/<feature>/\`.

## Git Actions (HARD RULE)
NEVER run \`git commit\`, \`git add\`, \`git push\`, \`git rebase\`, \`git reset\`, \`git tag\`, or any other git command in this pipeline context. The pipeline runner is responsible for version control. You may only create/edit the generated files in the target output directory. If subagents try to commit, REFUSE.
`
