/**
 * Oracle Plan Template
 *
 * The markdown template structure for work plans generated by Oracle.
 * The skeleton (headings, task grammar, QA guidance) is generated by
 * renderPlanSkeleton so it can never drift from the plan contract; this
 * module only wraps it in the Oracle-facing prose and code fence.
 */
import { renderPlanSkeleton } from "../../features/plan-contract/skeleton"

export const ORACLE_PLAN_TEMPLATE = `## Plan Structure

Generate plan via plan_create to: \`.matrixx/plans/{name}.md\`

\`\`\`markdown
${renderPlanSkeleton()}
\`\`\`

---`
